version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '9292:9292'
      - '8080:8080'
    volumes:
      - .:/usr/src/bookman
      - ./vendor/bundle:/usr/local/bundle
#    env_file: .env
#    depends_on:
#      - db
#  db:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
