# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd7cb546c631e949577d9150f5ce22ea238b5115b6e108b1c372e7b32c0dbb58690565b7fc895e0067775da14e3aad3c7d849b6024ce59b8a2956b909c702e68

test:
  secret_key_base: 47973bdbac55a2223d397eb5554ed822b8afdd3490852e68f833fc44d92b5b472105f6a4b18bdc9f0820fea5ccb7f3074d092edbae7585f7df5f5b2ff1c53b5c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
